import configparser
import os
import os.path as op
from contextlib import redirect_stdout

from pipreqs.pipreqs import __doc__, __version__, docopt, init


def main():
    build_requirements()
    build_metadata()
    build_readme()


def build_readme():
    from src.parcoords import parcoords

    cfg = configparser.ConfigParser()
    cfg.read("setup.cfg")
    with open(op.join(op.dirname(__file__), "README"), "w") as f:
        f.write(cfg["metadata"]["name"] + "\n\n")
        with redirect_stdout(f):
            parcoords.main(["-?"])


def build_metadata():
    cfg = configparser.ConfigParser()
    cfg.read("setup.cfg")
    lines = ["# this file is autogenerated by .pre-commit.py"]
    lines.append('"""')
    lines.append(cfg["metadata"]["description"])
    lines.append('"""')
    lines.append('__version__ = "' + cfg["metadata"]["version"] + '"')
    lines.append("")
    open("src/parcoords/__metadata__.py", "w").write("\n".join(lines))


def build_requirements():
    wd = op.dirname(__file__)
    dst = op.join(wd, "requirements.txt")
    try:
        os.remove(dst)
    except FileNotFoundError:
        pass

    # this is a copy of the pipreqs main fcn, but we pass our own argv to docopt
    args = docopt(__doc__, argv=[], version=__version__)
    init(args)
    unsorted = open(dst, "r").readlines()
    sortedlst = ["# this file is autogenerated by .pre-commit.py\n"] + sorted(unsorted)
    open(dst, "w").write("".join(sortedlst))


if __name__ == "__main__":
    main()
